application: govhacktumbleweed
version: v1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: endpoint.APPLICATION

libraries:
- name: webapp2
  version: latest

#dummy change 
